### ISSUE TITLE
对标wox的有道翻译插件，缺失常用功能

### ISSUE THREAD

**Issue by ZgblKylin** [qjcXu/Flow.Launcher.Translation#6]
我之前最常用的是wox里的[有道翻译](https://github.com/Wox-launcher/Wox.Plugin.Youdao)，相比之下缺少了一些很方便的功能，导致使用繁琐很多：

1. 默认语言自动互译

例如常用模式为中英互译，那么是否可以配置为自动互译，然后就省去`tr auto en`和`tr auto zh`的麻烦，每次可以`tr test`或者`tr 测试`，然后自动匹配到互译对里的另一种语言。

更进一步，还可以指定默认语言，那么未在互译对里的语言默认翻译为指定语言，比如`tr Тест`，也会将俄语翻译为中文。

从配置角度，可以考虑设置为首选语言和次选语言，那么这两个语言之间就可以自动互译，其他语言则翻译为首选语言：

```javascript
"first_language": "zh-CN",
"second_language": "en-US"
```

2. 回车复制翻译内容

这个不用多说明了吧，翻译插件很多时候也需要复制翻译后的内容，这个插件目前没发现有这项功能。

**Comment by lukxu** [comment]
1.默认语言自动互译这个应该很快就可以做出来。
2.回车复制内容，之前我有过这个想法，当时因为没找到对应的接口所有没做出来。
有时间了，我再重新做下这个插件吧

**Comment by lukxu** [comment]
> 我之前最常用的是wox里的[有道翻译](https://github.com/Wox-launcher/Wox.Plugin.Youdao)，相比之下缺少了一些很方便的功能，导致使用繁琐很多：
> 
> 1. 默认语言自动互译
> 
> 例如常用模式为中英互译，那么是否可以配置为自动互译，然后就省去`tr auto en`和`tr auto zh`的麻烦，每次可以`tr test`或者`tr 测试`，然后自动匹配到互译对里的另一种语言。
> 
> 更进一步，还可以指定默认语言，那么未在互译对里的语言默认翻译为指定语言，比如`tr Тест`，也会将俄语翻译为中文。
> 
> 从配置角度，可以考虑设置为首选语言和次选语言，那么这两个语言之间就可以自动互译，其他语言则翻译为首选语言：
> 
> ```js
> "first_language": "zh-CN",
> "second_language": "en-US"
> ```
> 
> 2. 回车复制翻译内容
> 
> 这个不用多说明了吧，翻译插件很多时候也需要复制翻译后的内容，这个插件目前没发现有这项功能。

我已经发布了最新的版本实现了上面的功能
你下载最新版本就可以了

**Comment by ZgblKylin** [comment]
大佬6666
